apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-env
  namespace: rca-agent
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: backend-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: rca-agent/backend-env
